# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95566ce717835d6fabad55ea620ad30ec3b70fb8e5e7fd94cd1708acda77797330b48d20525b081d3d9028f9e4d6b8caf84ba22ad02ccb641df433f65f7a8737

test:
  secret_key_base: bf1dcf73f2884806bfed3ce47ccc6179c62b8986a918e5622a0e1fd69e48e9eecc0cea11fd93d4a130bd65b6fff6ed92f50e237ae55d95b2a718fb43f7b93cfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
